workflows:
  android:
    name: Build Android APK
    environment:
      flutter: stable
    scripts:
      - name: Create Flutter platform folders if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
